appointments/urls.py
from django.urls import path, include

from appointments.views import make_appointment_page, make_appointment_ajax, \
    appointment_detail_page_doc, appointment_detail_page_pat, contact_patient_page, all_appointments_page, \
    appointment_successful_page, make_appointment_post, withdraw_appointment_pat, appointment_medium_page_admin, \
    add_appointment_medium_page_admin, appointment_video_call_page, appointment_text_message_page, \
    appointment_text_message_page_doc, approve_appointment_doc, all_appointments_admin_page, \
    appointment_detail_page_admin

app_name = "appointments"

urlpatterns = [
    path("all_appointments/", all_appointments_page, name="all_appointments"),
    path("all_appointments_admin/", all_appointments_admin_page, name="all_appointments_admin"),
    path("make_appointment/", make_appointment_page, name="make_appointment"),
    path("make_appointment_post/", make_appointment_post, name="make_appointment_post"),
    path("appointment_successful/", appointment_successful_page, name="appointment_successful"),
    path("appointment_detail_doc/<id>/", appointment_detail_page_doc, name="appointment_detail_doc"),
    path("appointment_detail_admin/<id>/", appointment_detail_page_admin, name="appointment_detail_admin"),

    path("appointment_detail_pat/<id>/", appointment_detail_page_pat, name="appointment_detail_pat"),
    path("withdraw_appointment_pat/<id>/", withdraw_appointment_pat, name="withdraw_appointment_pat"),
    path("contact_patient/", contact_patient_page, name="contact_patient"),

    path("make_appointment/", make_appointment_ajax, name="make_appointment_ajax"),

    path("appointment_medium_page_admin/", appointment_medium_page_admin, name="appointment_medium_page_admin"),
    path("add_appointment_medium_page_admin/", add_appointment_medium_page_admin, name="add_appointment_medium_page_admin"),

    path("appointment_video_call_page/", appointment_video_call_page,
         name="appointment_video_call_page"),
    path("appointment_text_message_page/<id>", appointment_text_message_page,
         name="appointment_text_message_page"),
    path("appointment_text_message_page_doc/<id>", appointment_text_message_page_doc,
         name="appointment_text_message_page_doc"),

    path("approve_appointment_doc/<id>/", approve_appointment_doc, name="approve_appointment_doc"),

]

home_page/urls.py
from django.urls import path, include

from home_page.views import home_page, patient_home_page, doctor_home_page, admin_home_page

app_name = "home_page"

urlpatterns = [
    path("", home_page, name="home_page"),
    path("patient_home/", patient_home_page, name="patient_home"),
    path("doctor_home/", doctor_home_page, name="doctor_home"),
    path("admin_home/", admin_home_page, name="admin_home"),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from mysite.views import welcome_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", welcome_page, name="welcome_page"),

    path("home/",  include('home_page.urls', 'home_page')),
    path("accounts/",  include('accounts.urls', 'accounts')),
    path("user_profile/", include('user_profile.urls', 'user_profile')),
    path("posts/", include('posts.urls', 'posts')),
    path("search/", include('search.urls', 'search')),
    path("appointments/", include('appointments.urls', 'appointments')),
    path("general_checkup/", include('general_checkup.urls', 'general_checkup')),
    path("prescriptions/", include('prescriptions.urls', 'prescriptions')),
    path("medical_centers/", include('medical_centers.urls', 'medical_centers')),
    path("communications/", include('communications.urls', 'communications')),
    path("financials/", include('financials.urls', 'financials')),

    # REST-framework
    path('api/accounts/', include('accounts.api.urls', 'accounts_api')),




]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include

from home_page.views import home_page
from posts.views import articles_page_pat, article_detail_page_pat, articles_page_doc, article_detail_page_doc, \
    add_article_page_doc, article_detail_page_admin, articles_page_admin, add_article_page_admin, add_article_post

app_name = "posts"

urlpatterns = [
    path("all_articles_pat/", articles_page_pat, name="all_articles_pat"),
    path("article_detail_pat/<article_id>/", article_detail_page_pat, name="article_detail_pat"),

    path("all_articles_doc/", articles_page_doc, name="all_articles_doc"),
    path("all_articles_admin/", articles_page_admin, name="all_articles_admin"),
    path("article_detail_doc/<article_id>/", article_detail_page_doc, name="article_detail_doc"),
    path("article_detail_admin/<article_id>/", article_detail_page_admin, name="article_detail_admin"),

    path("add_article_doc/", add_article_page_doc, name="add_article_doc"),

    path("add_article_post/", add_article_post, name="add_article_post"),
    path("add_article_admin/", add_article_page_admin, name="add_article_admin"),

]

appointments/views.py
import json

from django.contrib.auth import get_user_model
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime

from appointments.api.serializers.appointment_detail_serializers import AppointmentDetailSerializer
from appointments.models import Appointment, AppointmentForOther, Payment, AppointmentMedium
from home_page.api.doc_home_serializers import ListDocAppointmentHomeSerializer
from recent_activities.models import RecentActivity
from user_profile.models import Doctor



User = get_user_model()


@csrf_exempt
def all_appointments_page(request):

    context = {}

    doctor = Doctor.objects.get(user=request.user.id)
    appointments_data = []
    doc_appointments = Appointment.objects.filter(doctor=doctor).order_by('-id')
    serializers = ListDocAppointmentHomeSerializer(doc_appointments, many=True)
    appointment_seria = serializers.data
    appointments_data = appointment_seria

    context["appointments_data"] = appointments_data

    return render(request, 'appointments/all_appointments.html', context)


@csrf_exempt
def all_appointments_admin_page(request):

    context = {}


    appointments_data = []
    appointments_data = Appointment.objects.all().order_by('id')


    context["appointments_data"] = appointments_data

    return render(request, 'appointments/all_appointments_admin.html', context)



@csrf_exempt
def make_appointment_page(request):
    context = {}


    return render(request, 'appointments/make_appointment.html', context)

@csrf_exempt
def make_appointment_post(request):
    context = {}
    if request.method == "POST":

        appointment_type = request.POST['appointment_type']
        doctor_id = request.POST['doctor']
        appointment_date = request.POST['appointment_date']
        appointment_time = request.POST['appointment_time']
        reason = request.POST['reason']
        for_self = request.POST['for_self']

        other_data_last_name = request.POST['other_data[last_name]']
        other_data_first_name = request.POST['other_data[first_name]']
        other_data_email = request.POST['other_data[email]']
        other_data_phone = request.POST['other_data[phone]']

        appointment_medium = request.POST['appointment_medium']
        appointment_price = request.POST['appointment_price']
        payment_type = request.POST['payment_type']

        payment_data_last_name = request.POST['payment_data[last_name]']
        payment_data_first_name = request.POST['payment_data[first_name]']
        payment_data_email = request.POST['payment_data[email]']
        payment_data_phone = request.POST['payment_data[phone]']

        patient = get_object_or_404(User, id=request.user.id)
        doctor = get_object_or_404(Doctor, id=doctor_id)

        print(request.POST)

        new_appointment = Appointment.objects.create(
            patient=patient,
            doctor=doctor,
            appointment_type=appointment_type,
            appointment_date=appointment_date,
            appointment_time=appointment_time,
            reason=reason,
            for_self=for_self,
            appointment_medium=appointment_medium,
            amount_to_pay=appointment_price,
            payment_method=payment_type,
            status="Pending",
        )

        new_appointment.save()

        if for_self is False:
            appointment_for_other = AppointmentForOther.objects.create(
                appointment=new_appointment,
                last_name=other_data_last_name,
                first_name=other_data_first_name,
                email=other_data_email,
                phone=other_data_phone,
            )
            appointment_for_other.save()


        new_payment = Payment.objects.create(
            appointment=new_appointment,
            last_name=payment_data_last_name,
            first_name=payment_data_first_name,
            email=payment_data_email,
            phone=payment_data_phone,
            amount=appointment_price,
        )
        new_payment.save()

        RecentActivity.objects.create(
            user=patient,
            subject="New Appointment - Web",
            verb="You created a new appointment on the web"
        )
        return render(request, 'appointments/appointment_successful.html', context)

    return render(request, 'appointments/appointment_successful.html', context)


def appointment_successful_page(request):
    context = {}

    return render(request, 'appointments/appointment_successful.html', context)


def appointment_detail_page_doc(request, id):

    print(id)

    context = {}
    appointment_detail = get_object_or_404(Appointment, id=id)

    context['appointment_detail'] = appointment_detail

    return render(request, 'appointments/appointment_detail_doc.html', context)



def appointment_detail_page_admin(request, id):

    print(id)

    context = {}
    appointment_detail = get_object_or_404(Appointment, id=id)

    context['appointment_detail'] = appointment_detail

    return render(request, 'appointments/appointment_detail_admin.html', context)




def appointment_detail_page_pat(request, id):

    print(id)

    context = {}
    appointment_detail = get_object_or_404(Appointment, id=id)

    context['appointment_detail'] = appointment_detail

    return render(request, 'appointments/appointment_detail_pat.html', context)


@csrf_exempt
def withdraw_appointment_pat(request, id, *args, **kwargs):
    payload = {}
    user = request.user
    appointment = get_object_or_404(Appointment, id=id)

    if request.POST:
        try:
            action = request.POST.get("action")
            print(action)
            if action == "Withdraw Appointment":
                appointment.status = "Canceled"
                appointment.save()
                payload['result'] = "success"

                serializers = AppointmentDetailSerializer(appointment, many=False)

                if serializers:
                    data = serializers.data
                    payload['appointment_detail'] = data


        except Exception as e:
            print("exception: " + str(e))
            payload['result'] = "error"
            payload['exception'] = str(e)

    return HttpResponse(json.dumps(payload), content_type="application/json")




def contact_patient_page(request):

    print(id)

    context = {}


    return render(request, 'appointments/contact_patient.html', context)



def make_appointment_ajax(request):
    context = {}

    appointment_type = request.GET.get('appointment_type', None)
    print(appointment_type)

    data = {}
    data['appointment_type'] = "WOOOOOOOOO"

    return JsonResponse(data)




def appointment_medium_page_admin(request):

    context = {}

    appointment_medium = AppointmentMedium.objects.all()

    context['mediums'] = appointment_medium


    return render(request, 'appointments/appointment_medium_admin.html', context)




def add_appointment_medium_page_admin(request):
    context = {}
    if request.method == "POST":
        name = request.POST['name']
        price = request.POST['price']
        print(name)
        print(price)
        AppointmentMedium.objects.create(
            name=name,
            price=price
        )

        return redirect('appointments:appointment_medium_page_admin')


    return render(request, 'appointments/add_appointment_medium_admin.html', context)


def appointment_video_call_page(request):
    context = {}



    return render(request, 'appointments/appointment_video_call.html', context)


def appointment_text_message_page(request, id):
    context = {}

    print(id)




    appointment = Appointment.objects.get(id=id)
    chat_room = appointment.chat_room

    user_1 = chat_room.user1
    user_2 = chat_room.user2

    if user_1 != request.user.id:
        print("Send user 1")
        context['other_user'] = user_2

    elif user_2 != request.user.id:
        print("Send user 2")
        context['other_user'] = user_1

    context['chat_room'] = chat_room




    return render(request, 'appointments/appointment_text_message.html', context)



def appointment_text_message_page_doc(request, id):
    context = {}

    print(id)


    appointment = Appointment.objects.get(id=id)
    chat_room = appointment.chat_room

    user_1 = chat_room.user1
    user_2 = chat_room.user2

    if user_1 != request.user.id:
        print("Send user 1")
        context['other_user'] = user_1

    elif user_2 != request.user.id:
        print("Send user 2")
        context['other_user'] = user_2

    context['chat_room'] = chat_room




    return render(request, 'appointments/appointment_text_message_doc.html', context)




@csrf_exempt
def approve_appointment_doc(request, id, *args, **kwargs):
    payload = {}
    user = request.user
    appointment = get_object_or_404(Appointment, id=id)

    if request.POST:
        try:
            action = request.POST.get("action")
            print(action)
            if action == "Approve Appointment":
                appointment.status = "Approved"
                appointment.save()
                payload['result'] = "success"

            if action == "Decline Appointment":
                appointment.status = "Declined"
                appointment.save()
                payload['result'] = "success"

            if action == "Start Appointment":
                appointment.status = "Started"
                appointment.save()
                payload['result'] = "success"

            if action == "Complete Appointment":
                appointment.status = "Completed"
                appointment.save()
                payload['result'] = "success"

            serializers = AppointmentDetailSerializer(appointment, many=False)

            if serializers:
                data = serializers.data
                payload['appointment_detail'] = data

appointments/templates/appointments/add_appointment_medium_admin.html
{% extends "base2admin.html" %}
{% load static %}

{% block content %}

 <main id="main" class="main">

    <div class="pagetitle">
      <h1>Add Appointment Mediums</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item active">Appointment Mediums</li>
            <li class="breadcrumb-item active">Add Appointment Mediums</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

     <div class="col-lg-6">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Add Appointment Medium</h5>

              <!-- General Form Elements -->
              <form method='POST' action="{% url 'appointments:add_appointment_medium_page_admin' %}">{% csrf_token %}

                  <div class="row mb-3">
                  <label for="name" class="col-sm-2 col-form-label">Medium Name</label>
                  <div class="col-sm-10">
                    <input id="name" type="text" name="name" class="form-control" required>
                  </div>
                </div>

                   <div class="row mb-3">
                  <label for="price" class="col-sm-2 col-form-label">Price</label>
                  <div class="col-sm-10">
                    <input id="price" type="text" name="price" class="form-control" required>
                  </div>
                </div>



                <div class="row mb-3">
                  <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Add Medium</button>
                  </div>
                </div>

              </form><!-- End General Form Elements -->

            </div>
          </div>

        </div>


  </main><!-- End #main -->
{% endblock %}

appointments/templates/appointments/appointment_detail_admin.html
{% extends "base2admin.html" %}
{% load static %}
{% load home_data %}

{% block content %}


<main id="main" class="main">

    <div class="pagetitle">
        <h1>Appointment Details</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="index.html">Appointments</a></li>
                <li class="breadcrumb-item"><a href="index.html">Appointment Details</a></li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-8">
                <div class="row">
                    <!-- Appointments Card -->

                    <div>
                        <div class="card mb-3">

                            <div class="row g-0">
                                <div class="col-md-3">
                                    <img height="170" width="170" src={{appointment_detail.patient.personal_info.photo.url}}
                                         class="img-fluid rounded-start"
                                         alt="...">
                                </div>


                                <div class="col-md-9">
                                    <div class="card-body">
                                        <h5 class="card-title mb-0 pb-2">{{appointment_detail.patient.last_name}}
                                            {{appointment_detail.patient.first_name}}</h5>
                                        <h6 class="card-subtitle mb-2 text-muted">{{appointment_detail.appointment_type}}</h6>
                                        {% if appointment_detail.status == "Pending" %}
                                            <span class="badge rounded-pill bg-danger app_status">{{appointment_detail.status}}</span>
                                        {% elif appointment_detail.status == "Declined" %}
                                            <span class="badge rounded-pill bg-danger app_status">{{appointment_detail.status}}</span>
                                        {% else %}
                                        <span class="badge rounded-pill bg-success app_status">{{appointment_detail.status}}</span>
                                        {% endif %}
                                        <div class="col mt-3">
                                            <button type="button" class="btn btn-primary"><i
                                                    class="bi bi-clock me-1"></i> {{appointment_detail.appointment_date}}, {{appointment_detail.appointment_time}}
                                            </button>
                                        </div>
                                          <div class="col mt-3">
                                            <a type="button" href="{% url 'appointments:appointment_video_call_page' %}" class="btn btn-warning"><i
                                                    class="bi bi-camera-reels-fill me-1"></i> Video Call
                                            </a>
                                              <button  type="button" class="btn btn-info"><i
                                                    class="bi bi-telephone-fill me-1"></i>Voice Call
                                            </button>
                                            <a type="button" href="{% url 'appointments:appointment_text_message_page_doc' appointment_detail.id %}" class="btn btn-dark"><i
                                                    class="bi bi-chat-left-dots-fill me-1"></i>Text Message</a>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row g-0">
                                <div class="col-md-3">
                                    <img height="170" width="170" src={{appointment_detail.doctor.user.personal_info.photo.url}}
                                         class="img-fluid rounded-start"
                                         alt="...">
                                </div>


                                <div class="col-md-9">
                                    <div class="card-body">
                                        <h5 class="card-title mb-0 pb-2">{{appointment_detail.doctor.user.last_name}}
                                            {{appointment_detail.doctor.user.first_name}}</h5>
                                        <h6 class="card-subtitle mb-2 text-muted">{{appointment_detail.doctor.title}}</h6>

                                          <div class="col mt-3">
                                            <a type="button" href="{% url 'appointments:appointment_video_call_page' %}" class="btn btn-warning"><i
                                                    class="bi bi-camera-reels-fill me-1"></i> Video Call
                                            </a>
                                              <button  type="button" class="btn btn-info"><i
                                                    class="bi bi-telephone-fill me-1"></i>Voice Call
                                            </button>
                                            <a type="button" href="{% url 'appointments:appointment_text_message_page_doc' appointment_detail.id %}" class="btn btn-dark"><i
                                                    class="bi bi-chat-left-dots-fill me-1"></i>Text Message</a>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- End Appointments Card -->



                    <div class="mh-3">
                        <div class="card ">
                             <div class="filter">
                        <a class="icon" href="#" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots"></i> Actions</a>
                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow" style="">
                            <li class="dropdown-header text-start">
                                <h6>Actions</h6>
                            </li>
                            <form id="appointment_actions" action="{% url 'appointments:approve_appointment_doc' appointment_detail.id %}"></form>
                            <li><a id="approve" class="dropdown-item" href="#">Approve Appointment</a></li>
                            <li><a id="decline" class="dropdown-item" href="#">Decline Appointment</a></li>
                            <li><a id="start" class="dropdown-item" href="#">Start Appointment</a></li>
                            <li><a id="completed" class="dropdown-item" href="#">Complete Appointment</a></li>
                        </ul>
                    </div>


                            <div class="card-body">


                                <div class="pt-0">
                                    <h5 class="card-title pb-0">Appointment Type</h5>
                                    <p class="">{{appointment_detail.appointment_type}}</p>
                                    <hr>
                                </div>

                                 <div class="pt-0">
                                    <h5 class="card-title pb-0">Patient</h5>
                                    <p class="">{{appointment_detail.patient.last_name}} {{appointment_detail.patient.first_name}}</p>
                                    <hr>
                                </div>
                                 <div class="pt-0">
                                    <h5 class="card-title pb-0">Appointment Date</h5>
                                    <p class="">{{appointment_detail.appointment_date}}</p>
                                    <hr>
                                </div>
                                 <div class="pt-0">
                                    <h5 class="card-title pb-0">Appointment Time</h5>
                                    <p class="">{{appointment_detail.appointment_time}}</p>
                                    <hr>
                                </div>
                                 <div class="pt-0">
                                    <h5 class="card-title pb-0">Reason</h5>
                                    <p class="">{{appointment_detail.reason}}</p>
                                    <hr>
                                </div>
                                 <div class="pt-0">
                                    <h5 class="card-title pb-0">For self</h5>
                                    <p class="">{{appointment_detail.for_self}}</p>
                                    <hr>
                                </div>

                                 <div class="pt-0">
                                    <h5 class="card-title pb-0">Appointment for other patient info</h5>
                                     <div class="pt-0">
                                    <div class="container">
                                        <h5 class="card-title pb-0">Full Name</h5>
                                    <p class="">{{appointment_detail.appointment_for_other.last_name}} {{appointment_detail.appointment_for_other.first_name}}</p>
                                    <hr>
                                         <h5 class="card-title pb-0">Email</h5>
                                    <p class="">{{appointment_detail.appointment_for_other.email}}</p>
                                    <hr>
                                         <h5 class="card-title pb-0">Phone</h5>
                                    <p class="">{{appointment_detail.appointment_for_other.phone}}</p>

                                    </div>
                                </div>
                                    <hr>
                                </div>

                                 <div class="pt-0">
                                    <h5 class="card-title pb-0">Appointment Medium</h5>
                                    <p class="">{{appointment_detail.appointment_medium}}</p>
                                    <hr>
                                </div>

                                 <div class="pt-0">
                                    <h5 class="card-title pb-0">Amount to pay</h5>
                                    <p class="">Ghc {{appointment_detail.amount_to_pay}}</p>
                                    <hr>
                                </div>
                                <div class="pt-0">
                                    <h5 class="card-title pb-0">Payment Info</h5>
                                    <div class="container">
                                        <h5 class="card-title pb-0">Payment Method</h5>
                                    <p class="">{{appointment_detail.payment_method}}</p>
                                    <hr>
                                        <h5 class="card-title pb-0">Full Name</h5>
                                    <p class="">{{appointment_detail.appointment_payment.last_name}} {{appointment_detail.appointment_for_other.first_name}}</p>
                                    <hr>
                                         <h5 class="card-title pb-0">Email</h5>
                                    <p class="">{{appointment_detail.appointment_payment.email}}</p>
                                    <hr>
                                         <h5 class="card-title pb-0">Phone</h5>
                                    <p class="">{{appointment_detail.appointment_payment.phone}}</p>

                                    </div>
                                    <hr>
                                </div>


                            </div>
                        </div>
                    </div>


                </div>
            </div><!-- End Left side columns -->

            <!-- Right side columns -->
            <div class="col-lg-4">

              {% get_recent_activities request.user.id  %}

            </div><!-- End Right side columns -->

        </div>
    </section>

</main><!-- End #main -->

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src='{% static "assets2/js/appointment_detail_doc.js" %}'></script>


{% endblock content %}

appointments/templates/appointments/appointment_mediums.html
{% for medium in appointment_mediums %}
<div class="col-xxl-4 col-md-6">
    <div data-value="{{medium.name}}" id="medium-{{medium.id}}" onclick="setMedium('{{medium.name}}', '{{medium.price}}' )" class="card info-card app_type_btn sales-card app-mediums">
        <div class="card-body text-center pb-0">
            <h5 class="card-title">{{medium.name}}</h5>

        </div>


    </div>
</div>
{% endfor %}