appointments/urls.py
from django.urls import path, include

from appointments.views import make_appointment_page, make_appointment_ajax, \
    appointment_detail_page_doc, appointment_detail_page_pat, contact_patient_page, all_appointments_page, \
    appointment_successful_page, make_appointment_post, withdraw_appointment_pat, appointment_medium_page_admin, \
    add_appointment_medium_page_admin, appointment_video_call_page, appointment_text_message_page, \
    appointment_text_message_page_doc, approve_appointment_doc, all_appointments_admin_page, \
    appointment_detail_page_admin

app_name = "appointments"

urlpatterns = [
    path("all_appointments/", all_appointments_page, name="all_appointments"),
    path("all_appointments_admin/", all_appointments_admin_page, name="all_appointments_admin"),
    path("make_appointment/", make_appointment_page, name="make_appointment"),
    path("make_appointment_post/", make_appointment_post, name="make_appointment_post"),
    path("appointment_successful/", appointment_successful_page, name="appointment_successful"),
    path("appointment_detail_doc/<id>/", appointment_detail_page_doc, name="appointment_detail_doc"),
    path("appointment_detail_admin/<id>/", appointment_detail_page_admin, name="appointment_detail_admin"),

    path("appointment_detail_pat/<id>/", appointment_detail_page_pat, name="appointment_detail_pat"),
    path("withdraw_appointment_pat/<id>/", withdraw_appointment_pat, name="withdraw_appointment_pat"),
    path("contact_patient/", contact_patient_page, name="contact_patient"),

    path("make_appointment/", make_appointment_ajax, name="make_appointment_ajax"),

    path("appointment_medium_page_admin/", appointment_medium_page_admin, name="appointment_medium_page_admin"),
    path("add_appointment_medium_page_admin/", add_appointment_medium_page_admin, name="add_appointment_medium_page_admin"),

    path("appointment_video_call_page/", appointment_video_call_page,
         name="appointment_video_call_page"),
    path("appointment_text_message_page/<id>", appointment_text_message_page,
         name="appointment_text_message_page"),
    path("appointment_text_message_page_doc/<id>", appointment_text_message_page_doc,
         name="appointment_text_message_page_doc"),

    path("approve_appointment_doc/<id>/", approve_appointment_doc, name="approve_appointment_doc"),

]

general_checkup/urls.py
from django.urls import path, include

from general_checkup.views import general_checkup_view

app_name = "general_checkup"

urlpatterns = [
    path("", general_checkup_view, name="general_checkup"),

]

home_page/urls.py
from django.urls import path, include

from home_page.views import home_page, patient_home_page, doctor_home_page, admin_home_page

app_name = "home_page"

urlpatterns = [
    path("", home_page, name="home_page"),
    path("patient_home/", patient_home_page, name="patient_home"),
    path("doctor_home/", doctor_home_page, name="doctor_home"),
    path("admin_home/", admin_home_page, name="admin_home"),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from mysite.views import welcome_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", welcome_page, name="welcome_page"),

    path("home/",  include('home_page.urls', 'home_page')),
    path("accounts/",  include('accounts.urls', 'accounts')),
    path("user_profile/", include('user_profile.urls', 'user_profile')),
    path("posts/", include('posts.urls', 'posts')),
    path("search/", include('search.urls', 'search')),
    path("appointments/", include('appointments.urls', 'appointments')),
    path("general_checkup/", include('general_checkup.urls', 'general_checkup')),
    path("prescriptions/", include('prescriptions.urls', 'prescriptions')),
    path("medical_centers/", include('medical_centers.urls', 'medical_centers')),
    path("communications/", include('communications.urls', 'communications')),
    path("financials/", include('financials.urls', 'financials')),

    # REST-framework
    path('api/accounts/', include('accounts.api.urls', 'accounts_api')),




]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include

from home_page.views import home_page
from posts.views import articles_page_pat, article_detail_page_pat, articles_page_doc, article_detail_page_doc, \
    add_article_page_doc, article_detail_page_admin, articles_page_admin, add_article_page_admin, add_article_post

app_name = "posts"

urlpatterns = [
    path("all_articles_pat/", articles_page_pat, name="all_articles_pat"),
    path("article_detail_pat/<article_id>/", article_detail_page_pat, name="article_detail_pat"),

    path("all_articles_doc/", articles_page_doc, name="all_articles_doc"),
    path("all_articles_admin/", articles_page_admin, name="all_articles_admin"),
    path("article_detail_doc/<article_id>/", article_detail_page_doc, name="article_detail_doc"),
    path("article_detail_admin/<article_id>/", article_detail_page_admin, name="article_detail_admin"),

    path("add_article_doc/", add_article_page_doc, name="add_article_doc"),

    path("add_article_post/", add_article_post, name="add_article_post"),
    path("add_article_admin/", add_article_page_admin, name="add_article_admin"),

]

prescriptions/urls.py
from django.urls import path, include

from prescriptions.views import prescriptions_view

app_name = "prescriptions"

urlpatterns = [
    path("", prescriptions_view, name="prescriptions"),

]

user_profile/urls.py
from django.urls import path, include

from user_profile.views import patient_profile_page, list_all_doctors_ajax, doctor_profile_page, add_timeslot_doc, \
    view_timeslot_doc, admin_profile_page, list_all_doctors_admin, doctor_detail_admin, \
    list_all_patients_admin, patient_detail_admin, list_all_doctors_schedule_admin

app_name = "user_profile"

urlpatterns = [
    path("patient_profile/", patient_profile_page, name="patient_profile"),
    # path('patient_profile/<user_id>/edit/cropImage/', crop_image, name="crop_image"),
    path("doctor_profile/", doctor_profile_page, name="doctor_profile"),
    path("admin_profile/", admin_profile_page, name="admin_profile"),
    #path("doctor_profile/", DoctorProfileView.as_view(), name="doctor_profile"),
    path("list_all_doctors_ajax/", list_all_doctors_ajax, name="list_all_doctors_ajax"),

    path("add_timeslot_doc/", add_timeslot_doc, name="add_timeslot_doc"),
    path("view_timeslot_doc/", view_timeslot_doc, name="view_timeslot_doc"),


    path("list_all_doctors_admin/", list_all_doctors_admin, name="list_all_doctors_admin"),
    path("doctor_detail_admin/<id>/", doctor_detail_admin, name="doctor_detail_admin"),

    path("list_all_patients_admin/", list_all_patients_admin, name="list_all_patients_admin"),
    path("patient_detail_admin/<id>/", patient_detail_admin, name="patient_detail_admin"),

    path("list_all_doctors_schedule_admin/", list_all_doctors_schedule_admin, name="list_all_doctors_schedule_admin"),

]

home_page/models.py
from django.db import models

# Create your models here.

home_page/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render

from appointments.models import Appointment
from home_page.api.patient_home_serializers import ListUserAppointmentHomeSerializer
from user_profile.models import PersonalInfo

User = get_user_model()


def home_page(request):
    context = {}

    return render(request, 'home_page/home_page.html', context)


def patient_home_page(request):
    context = {}


    user = User.objects.get(id=request.user.id)
    personal_info = PersonalInfo.objects.get(user=user)

    appointment_data = []
    user_appointments = Appointment.objects.filter(patient=request.user.id).order_by('-id')[:5]
    serializers = ListUserAppointmentHomeSerializer(user_appointments, many=True)
    appointment_seria = serializers.data
    appointment_data = appointment_seria

    context['appointment_data'] = appointment_data



    user_data = {}
    user_data["last_name"] = user.last_name
    user_data["first_name"] = user.first_name
    user_data['photo'] = personal_info.photo.url

    context['user_data'] = user_data

    return render(request, 'home_page/patient_home_page.html', context)


def doctor_home_page(request):
    context = {}

    return render(request, 'home_page/doctor_home_page.html', context)


def admin_home_page(request):
    context = {}

    return render(request, 'home_page/admin_home_page.html', context)

home_page/templates/home_page/doctor_home_page.html
{% extends "base2doc.html" %}
{% load static %}

{% load home_data %}


{% block content %}


<main id="main" class="main">

    <div class="pagetitle">
      <h1>Welcome back {{ request.user.first_name }}</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

  <h5 class="card-title">Top Services - Doctor</h5>

    <section class="section dashboard">
      <div class="row">

        <!-- Left side columns -->
        <div class="col-lg-8">
          <div class="row">

            <!-- Make appointment Card -->

              <div class="col-xxl-6 col-md-6">
                <a href="{% url 'user_profile:add_timeslot_doc' %}">
              <div class="card info-card sales-card">

                <div class="card-body">
                  <h5 class="card-title">Add Time slot</h5>

                  <div class="d-flex align-items-center">
                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                      <i class="bi bi-calendar-plus"></i>
                    </div>
                  </div>
                </div>

              </div>
                </a>
            </div>


            <!-- End Make an appointment -->
            <!-- General Checkup Card -->
            <div class="col-xxl-6 col-md-6">
              <a href="{% url 'user_profile:view_timeslot_doc' %}">
              <div class="card info-card sales-card">

                <div class="card-body">
                  <h5 class="card-title">View Time slots</h5>

                  <div class="d-flex align-items-center">
                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                      <i class="bi bi-calendar-week"></i>
                    </div>
                  </div>
                </div>

              </div>
              </a>
            </div><!-- End General checkup Card -->

            <!-- Prescriptions Card -->
            <div class="col-xxl-6 col-md-6">
              <a href="{% url 'appointments:contact_patient' %}">
              <div class="card info-card sales-card">

                <div class="card-body">
                  <h5 class="card-title">Contact Patient</h5>

                  <div class="d-flex align-items-center">
                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                      <i class="bi bi-people"></i>
                    </div>
                  </div>
                </div>

              </div>
              </a>
            </div><!-- End Prescriptions Card -->

            <!-- Medical Centers Card -->
            <div class="col-xxl-6 col-md-6">
               <a href="{% url 'posts:all_articles_doc' %}">
              <div class="card info-card sales-card">

                <div class="card-body">
                  <h5 class="card-title">View Articles</h5>

                  <div class="d-flex align-items-center">
                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                      <i class="bi bi-journal-medical"></i>
                    </div>
                  </div>
                </div>

              </div>
               </a>
            </div><!-- End Medical Centers  Card -->

            <h5 class="card-title col">My Appointments <span>| <a href="{% url 'appointments:all_appointments' %}">See all</a></span></h5>


            {% get_recent_appointments_doc request.user.id  %}




          </div>
        </div><!-- End Left side columns -->

        <!-- Right side columns -->
        <div class="col-lg-4">

          {% get_recent_activities request.user.id  %}

        </div><!-- End Right side columns -->

      </div>
    </section>

  </main><!-- End #main -->

{% endblock content %}

home_page/templates/home_page/patient_home_page.html
{% extends "base2pat.html" %}
{% load static %}
{% load home_data %}





{% block content %}


<main id="main" class="main">

    <div class="pagetitle">
        <h1>Welcome back {{ request.user.first_name }}</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <h5 class="card-title">Top Services - Patient</h5>

    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-8">
                <div class="row">

                    <!-- Make appointment Card -->
                    <div class="col-xxl-6 col-md-6">
                        <a href='{% url "appointments:make_appointment" %}'>
                            <div class="card info-card sales-card">

                                <div class="card-body">
                                    <h5 class="card-title">Make an appointment</h5>

                                    <div class="d-flex align-items-center">
                                        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                            <i class="bi bi-calendar-week"></i>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </a>
                    </div><!-- End Make an appointment -->
                    <!-- General Checkup Card -->
                    <div class="col-xxl-6 col-md-6">
                        <a href='{% url "general_checkup:general_checkup" %}'>
                            <div class="card info-card sales-card">

                                <div class="card-body">
                                    <h5 class="card-title">General Checkup</h5>

                                    <div class="d-flex align-items-center">
                                        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                            <i class="bi bi-bookmark-heart"></i>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </a>
                    </div><!-- End General checkup Card -->

                    <!-- Prescriptions Card -->
                    <div class="col-xxl-6 col-md-6">
                        <a href='{% url "prescriptions:prescriptions" %}'>
                            <div class="card info-card sales-card">

                                <div class="card-body">
                                    <h5 class="card-title">Prescriptions</h5>

                                    <div class="d-flex align-items-center">
                                        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                            <i class="bi bi-journal-medical"></i>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </a>
                    </div><!-- End Prescriptions Card -->

                    <!-- Medical Centers Card -->
                    <div class="col-xxl-6 col-md-6">
                        <a href='{% url "medical_centers:medical_centers" %}'>
                            <div class="card info-card sales-card">

                                <div class="card-body">
                                    <h5 class="card-title">Medical Centers</h5>

                                    <div class="d-flex align-items-center">
                                        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                            <i class="bi bi-building"></i>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </a>
                    </div><!-- End Medical Centers  Card -->

                    <p id="demo"></p>

                    <h5 class="card-title col">My Appointments <span>| See all</span></h5>

                    <!-- Appointments Card -->

                    <div>
                        {% if appointment_data %}
                            {% for appointment in appointment_data %}
                              <a href='{% url "appointments:appointment_detail_pat" appointment.id %}'>
                                  <div class="card mb-3">
                            <div class="row g-0">
                                <div class="col-md-3">
                                    <img height="170" width="170" src={{appointment.doctor.user.personal_info.photo}} class="img-fluid rounded-start"
                                         alt="...">
                                </div>


                                <div class="col-md-9">
                                    <div class="card-body">
                                        <h5 class="card-title mb-0 pb-2">Dr. {{appointment.doctor.user.last_name}} {{appointment.doctor.user.first_name}}</h5>
                                        <h6 class="card-subtitle mb-2 text-muted">{{appointment.doctor.title}}</h6>
                                        {% if appointment.status == "Pending" %}
                                            <span class="badge rounded-pill bg-danger">{{appointment.status}}</span>
                                        {% elif appointment.status == "Declined" %}
                                            <span class="badge rounded-pill bg-danger">{{appointment.status}}</span>
                                        {% else %}
                                            <span class="badge rounded-pill bg-success">{{appointment.status}}</span>
                                        {% endif %}
                                        <div class="col mt-3">
                                            <button type="button" class="btn btn-primary"><i
                                                    class="bi bi-clock me-1"></i> {{appointment.appointment_date}}, {{ appointment.appointment_time }}
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                              </a>

                            {% endfor %}
                        {% else %}
                        <div class="card mb-3">
                            <div class="row g-0">
                                <div class="col-md-9">
                                    <div class="card-body">
                                        <h5 class="card-title mb-0 pb-2">No Appointment available</h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                    <!-- End Appointments Card -->


                </div>
            </div><!-- End Left side columns -->

            <!-- Right side columns -->
        <div class="col-lg-4">

          {% get_recent_activities request.user.id %}

        </div><!-- End Right side columns -->

        </div>
    </section>

</main><!-- End #main -->

<script>
    function convertDate(date){

    console.log(date);

    return date;
    }
</script>

{% endblock content %}

home_page/templates/home_page/recent_activities.html
<!-- Recent Activity -->
          <div class="card">
            <div class="filter">
              <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
              <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <li class="dropdown-header text-start">
                  <h6>Filter</h6>
                </li>

                <li><a class="dropdown-item" href="#">Today</a></li>
                <li><a class="dropdown-item" href="#">This Month</a></li>
                <li><a class="dropdown-item" href="#">This Year</a></li>
              </ul>
            </div>


            <div class="card-body">
              <h5 class="card-title">Recent Activity</h5>

              <div class="activity">

                {% for activity in recent_activities %}
                  <div class="activity-item d-flex">
                  <div class="activite-label">{{activity.timestamp|timesince}}</div>
                  <i class='bi bi-circle-fill activity-badge text-success align-self-start'></i>
                  <div class="activity-content">
                      {{activity.verb}}
                  </div>
                </div><!-- End activity item-->
                {% endfor %}

              </div>

            </div>

          </div><!-- End Recent Activity -->

home_page/templates/home_page/recent_appointments_doc.html
{% load static %}

<!-- Appointments Card -->

           <div>
               {% if appointments_data %}
                    {% for appointment in appointments_data %}
                        <a href='{% url "appointments:appointment_detail_doc" appointment.id %}'>
                                  <div class="card mb-3">
                            <div class="row g-0">
                                <div class="col-md-3">
                                    <img height="170" width="170" src={{appointment.patient.personal_info.photo}} class="img-fluid rounded-start"
                                         alt="...">
                                </div>


                                <div class="col-md-9">
                                    <div class="card-body">
                                        <h5 class="card-title mb-0 pb-2">{{appointment.patient.last_name}} {{appointment.patient.first_name}}</h5>
                                        <h6 class="card-subtitle mb-2 text-muted">{{appointment.appointment_type}}</h6>
                                        {% if appointment.status == "Pending" %}
                                            <span class="badge rounded-pill bg-danger">{{appointment.status}}</span>
                                        {% elif appointment.status == "Declined" %}
                                            <span class="badge rounded-pill bg-danger">{{appointment.status}}</span>
                                        {% else %}
                                            <span class="badge rounded-pill bg-success">{{appointment.status}}</span>
                                        {% endif %}
                                        <div class="col mt-3">
                                            <button type="button" class="btn btn-primary"><i
                                                    class="bi bi-clock me-1"></i> {{appointment.appointment_date}}, {{ appointment.appointment_time }}
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                              </a>

                    {% endfor %}
               {% else %}

                <div class="card mb-3">
            <div class="row g-0">

              <div class="col-md-9">
                <div class="card-body">
                  <h5 class="card-title mb-0 pb-2">No Appointments Available</h5>
                </div>
              </div>
            </div>
          </div>

               {% endif %}

           </div>
            <!-- End Appointments Card -->