accounts/api/urls.py
from django.urls import path

from accounts.api.views.admin_views import registration_admin_view, ObtainAdminAuthTokenView
from accounts.api.views.doc_views import doc_registration_view, ObtainDocAuthTokenView, logout_doc_view_api
from accounts.api.views.patient_views import patient_registration_view, ObtainPatientAuthTokenView, \
    logout_patient_view_api, patient_registration_validate_email

app_name = 'accounts'

urlpatterns = [
    path('register_patient', patient_registration_view, name="register_patient"),
    path('patient_registration_validate_email', patient_registration_validate_email,
         name="patient_registration_validate_email"),

    path('register_doc', doc_registration_view, name="register_doc"),
    path('register_admin', registration_admin_view, name="register_admin"),

    path('login_patient', ObtainPatientAuthTokenView.as_view(), name="login_patient"),
    path('login_doc', ObtainDocAuthTokenView.as_view(), name="login_doc"),
    path('login_admin', ObtainAdminAuthTokenView.as_view(), name="login_admin"),

    path('logout_patient', logout_patient_view_api, name="logout_patient"),
    path('logout_doc', logout_doc_view_api, name="logout_doc"),
    path('logout_admin', logout_doc_view_api, name="logout_admin"),
    #path('email/resend-activation/', account_email_activation_view, name="resend-activation'"),
    #path('password/change_password/', change_password_view, name="change_password"),
]

accounts/urls.py
from django.urls import path, include

from accounts.views import LoginPatientView, RegisterPatientView, logout_patient_view, LoginDoctorView, \
    RegisterDoctorView, logout_doctor_view, RegisterAdminView, LoginAdminView

app_name = "accounts"

urlpatterns = [
    path("login_patient/", LoginPatientView.as_view(), name="login_patient"),
    path("login_doctor/", LoginDoctorView.as_view(), name="login_doctor"),
    path("login_admin/", LoginAdminView.as_view(), name="login_admin"),

    path("logout_patient/", logout_patient_view, name="logout_patient"),
    path("logout_doctor/", logout_doctor_view, name="logout_doctor"),

    path("register_patient/", RegisterPatientView.as_view(), name="register_patient"),
    path("register_doctor/", RegisterDoctorView.as_view(), name="register_doctor"),
    path("register_admin/", RegisterAdminView.as_view(), name="register_admin"),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from mysite.views import welcome_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", welcome_page, name="welcome_page"),

    path("home/",  include('home_page.urls', 'home_page')),
    path("accounts/",  include('accounts.urls', 'accounts')),
    path("user_profile/", include('user_profile.urls', 'user_profile')),
    path("posts/", include('posts.urls', 'posts')),
    path("search/", include('search.urls', 'search')),
    path("appointments/", include('appointments.urls', 'appointments')),
    path("general_checkup/", include('general_checkup.urls', 'general_checkup')),
    path("prescriptions/", include('prescriptions.urls', 'prescriptions')),
    path("medical_centers/", include('medical_centers.urls', 'medical_centers')),
    path("communications/", include('communications.urls', 'communications')),
    path("financials/", include('financials.urls', 'financials')),

    # REST-framework
    path('api/accounts/', include('accounts.api.urls', 'accounts_api')),




]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include

from home_page.views import home_page
from posts.views import articles_page_pat, article_detail_page_pat, articles_page_doc, article_detail_page_doc, \
    add_article_page_doc, article_detail_page_admin, articles_page_admin, add_article_page_admin, add_article_post

app_name = "posts"

urlpatterns = [
    path("all_articles_pat/", articles_page_pat, name="all_articles_pat"),
    path("article_detail_pat/<article_id>/", article_detail_page_pat, name="article_detail_pat"),

    path("all_articles_doc/", articles_page_doc, name="all_articles_doc"),
    path("all_articles_admin/", articles_page_admin, name="all_articles_admin"),
    path("article_detail_doc/<article_id>/", article_detail_page_doc, name="article_detail_doc"),
    path("article_detail_admin/<article_id>/", article_detail_page_admin, name="article_detail_admin"),

    path("add_article_doc/", add_article_page_doc, name="add_article_doc"),

    path("add_article_post/", add_article_post, name="add_article_post"),
    path("add_article_admin/", add_article_page_admin, name="add_article_admin"),

]

accounts/api/views/admin_views.py
from django.contrib.auth import get_user_model, authenticate, logout
from rest_framework.authentication import TokenAuthentication
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.api.serializers import PatientRegistrationSerializer, DocRegistrationSerializer, AdminRegistrationSerializer
from accounts.models import EmailActivation
from recent_activities.models import RecentActivity
from user_profile.models import PersonalInfo

User = get_user_model()

class ObtainAdminAuthTokenView(APIView):
    authentication_classes = []
    permission_classes = []

    def post(self, request):
        payload = {}
        data = {}

        email = request.data.get('email', '0')
        password = request.data.get('password', '0')

        qs = User.objects.filter(email=email)

        if qs.exists():
            not_active = qs.filter(is_active=False)
            if not_active.exists():
                reconfirm_msg = "resend confirmation email"
                confirm_email = EmailActivation.objects.filter(email=email)
                is_confirmable = confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1 = "Please check your email to confirm your account or " + reconfirm_msg.lower()
                    payload['response'] = "Error"
                    payload['error_message'] = msg1
                    return Response(payload)
                email_confirm_exists = EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2 = "Email not confirmed. " + reconfirm_msg
                    payload['response'] = "Error"
                    payload['error_message'] = msg2
                    return Response(payload)
                if not is_confirmable and not email_confirm_exists:
                    payload['response'] = "Error"
                    payload['error_message'] = "This user is inactive."
                    return Response(payload)

            if qs.first().admin is not True:
                payload['response'] = "Error"
                payload['error_message'] = "You are not an admin"
                return Response(payload)

        print(email, password)



        user = authenticate(email=email, password=password)
        RecentActivity.objects.create(
            user=user,
            subject="Admin login - Mobile",
            verb="You logged in on mobile"
        )
        if user:
            try:
                token = Token.objects.get(user=user)
            except Token.DoesNotExist:
                token = Token.objects.create(user=user)

            try:
                personal_info = PersonalInfo.objects.get(user=user)
            except PersonalInfo.DoesNotExist:
                personal_info = PersonalInfo.objects.create(user=user)

            payload['response'] = 'Successful'
            data['id'] = user.pk
            data['username'] = user.username
            data['email'] = user.email
            data['last_name'] = user.last_name
            data['first_name'] = user.first_name
            data['photo'] = personal_info.photo.url
            data['active'] = personal_info.active
            data['token'] = token.key
            payload['data'] = data
            print(payload)
        else:
            payload['response'] = 'Error'
            payload['error_message'] = 'Invalid credentials'
            print(payload)
        return Response(payload)



@api_view(['GET', ])
@permission_classes((IsAuthenticated, ))
@authentication_classes((TokenAuthentication,))
def logout_admin_view_api(request):
    payload = {}
    data = {}
    if request.method == 'GET':
        request.user.auth_token.delete()
        logout(request)
        payload['response'] = 'Successful'
    return Response(payload)



@api_view(['POST', ])
@permission_classes([])
@authentication_classes([])
def registration_admin_view(request):
    if request.method == 'POST':
        payload = {}
        data = {}
        email = request.data.get('email', '0').lower()
        if validate_email(email) != None:
            payload['error_message'] = 'That email is already in use.'
            payload['response'] = 'Error'
            return Response(payload)

        username = request.data.get('username', '0')
        if validate_username(username) != None:
            payload['error_message'] = 'That username is already in use.'
            payload['response'] = 'Error'
            return Response(payload)

        serializer = AdminRegistrationSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            payload['response'] = 'Successful'
            data['username'] = user.username
            data['email'] = user.email
            data['last_name'] = user.last_name
            data['first_name'] = user.first_name
            token = Token.objects.get(user=user).key
            data['token'] = token

            payload['data'] = data
        else:
            payload = serializer.errors
        return Response(payload)


def validate_email(email):
    user = None
    try:
        user = User.objects.get(email=email)
    except User.DoesNotExist:
        return None
    if user != None:
        return email


def validate_username(username):
    user = None
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return None
    if user != None:
        return username

accounts/api/views/doc_views.py
from django.contrib.auth import get_user_model, authenticate, logout
from rest_framework.authentication import TokenAuthentication
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.api.serializers import PatientRegistrationSerializer, DocRegistrationSerializer
from accounts.models import EmailActivation
from recent_activities.models import RecentActivity
from user_profile.models import PersonalInfo, Doctor

User = get_user_model()


@api_view(['POST', ])
@permission_classes([])
@authentication_classes([])
def doc_registration_view(request):
    if request.method == 'POST':
        payload = {}
        data = {}
        email = request.data.get('email', '0').lower()
        if validate_email(email) != None:
            payload['error_message'] = 'That email is already in use.'
            payload['response'] = 'Error'
            return Response(payload)

        username = request.data.get('username', '0')
        if validate_username(username) != None:
            payload['error_message'] = 'That username is already in use.'
            payload['response'] = 'Error'
            return Response(payload)

        serializer = DocRegistrationSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            payload['response'] = 'Successful'
            data['username'] = user.username
            data['email'] = user.email
            data['last_name'] = user.last_name
            data['first_name'] = user.first_name
            token = Token.objects.get(user=user).key
            data['token'] = token

            payload['data'] = data
        else:
            payload = serializer.errors
        return Response(payload)




def validate_email(email):
    user = None
    try:
        user = User.objects.get(email=email)
    except User.DoesNotExist:
        return None
    if user != None:
        return email


def validate_username(username):
    user = None
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return None
    if user != None:
        return username




class ObtainDocAuthTokenView(APIView):
    authentication_classes = []
    permission_classes = []

    def post(self, request):
        payload = {}
        data = {}

        email = request.data.get('email', '0')
        password = request.data.get('password', '0')

        qs = User.objects.filter(email=email)

        if qs.exists():
            not_active = qs.filter(is_active=False)
            if not_active.exists():
                reconfirm_msg = "resend confirmation email"
                confirm_email = EmailActivation.objects.filter(email=email)
                is_confirmable = confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1 = "Please check your email to confirm your account or " + reconfirm_msg.lower()
                    payload['response'] = "Error"
                    payload['error_message'] = msg1
                    return Response(payload)
                email_confirm_exists = EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2 = "Email not confirmed. " + reconfirm_msg
                    payload['response'] = "Error"
                    payload['error_message'] = msg2
                    return Response(payload)
                if not is_confirmable and not email_confirm_exists:
                    payload['response'] = "Error"
                    payload['error_message'] = "This user is inactive."
                    return Response(payload)

            try:
                doc = Doctor.objects.get(user=qs.first())
            except Doctor.DoesNotExist:
                payload['response'] = "Error"
                payload['error_message'] = "You are not a doctor"
                return Response(payload)

            print("######## THE DOC #######")
            print(doc)



        print(email, password)
        user = authenticate(email=email, password=password)
        RecentActivity.objects.create(
            user=user,
            subject="Doctor login - Mobile",
            verb="You logged in on mobile"
        )
        if user:
            try:
                token = Token.objects.get(user=user)
            except Token.DoesNotExist:
                token = Token.objects.create(user=user)

            try:
                personal_info = PersonalInfo.objects.get(user=user)
            except PersonalInfo.DoesNotExist:
                personal_info = PersonalInfo.objects.create(user=user)

            payload['response'] = 'Successful'
            data['id'] = user.pk
            data['username'] = user.username
            data['email'] = user.email
            data['last_name'] = user.last_name
            data['first_name'] = user.first_name
            data['photo'] = personal_info.photo.url
            data['active'] = personal_info.active
            data['token'] = token.key
            payload['data'] = data
            print(payload)
        else:
            payload['response'] = 'Error'
            payload['error_message'] = 'Invalid credentials'
            print(payload)
        return Response(payload)




@api_view(['GET', ])
@permission_classes((IsAuthenticated, ))
@authentication_classes((TokenAuthentication,))
def logout_doc_view_api(request):
    payload = {}
    data = {}
    user = request.user
    if request.method == 'GET':
        request.user.auth_token.delete()
        logout(request)

        RecentActivity.objects.create(
            user=user,
            subject="Patient logout - Mobile",
            verb="You Logged out on mobile"
        )
        payload['response'] = 'Successful'
    return Response(payload)

accounts/templates/accounts/login_admin.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>JadeCare - Login Admin</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    {% include "base/css2.html" %}
  <style>
    #top-message {
  z-index: 10;
    position: fixed;
    width: 100%;
  height:50px;
  left:50%;
  transform:translateX(-50%);
  top:10px;
}

  </style>
</head>

<body>

<div class="container" id="top-message">
   {% if messages %}
      <div class="alert alert-success messages alert-dismissible fade show" role="alert">
          {% for message in messages %}
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}<br/>
          </span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          {% endfor %}
      </div>
      {% endif %}
</div>



  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href='{% url "welcome_page" %}' class="logo d-flex align-items-center w-auto">
                  <img src="assets/img/logo.png" alt="">
                  <span class="d-none d-lg-block">JadeCare - Login Admin</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your email & password to login</p>
                  </div>

                  <form method='POST' class="row g-3 needs-validation" novalidate>{% csrf_token %}

                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Email</label>
                      <div class="input-group has-validation">
                        <input type="text" name="email" class="form-control" id="yourUsername" required>
                        <div class="invalid-feedback">Please enter your email.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">Remember me</label>
                      </div>
                    </div>
                    <div>
                       {% for field in form %}
                        <p>
                        {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                      </p>
                    {% endfor %}
                  {% if form.non_field_errors %}
                  <div style="color: red">
                  <p>{{form.non_field_errors}}</p>
                      </div>

                      {% endif %}

                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a href='{% url "accounts:register_admin" %}'>Create an account</a></p>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0"> <a href='{% url "welcome_page" %}'>Go to Home page</a></p>
                    </div>
                  </form>

                </div>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

 {% include "base/js2.html" %}

</body>

</html>

accounts/templates/accounts/login_doctor.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>JadeCare - Login Doctor</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    {% include "base/css2.html" %}
  <style>
    #top-message {
  z-index: 10;
    position: fixed;
    width: 100%;
  height:50px;
  left:50%;
  transform:translateX(-50%);
  top:10px;
}

  </style>
</head>

<body>

<div class="container" id="top-message">
   {% if messages %}
      <div class="alert alert-success messages alert-dismissible fade show" role="alert">
          {% for message in messages %}
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}<br/>
          </span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          {% endfor %}
      </div>
      {% endif %}
</div>



  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href='{% url "welcome_page" %}' class="logo d-flex align-items-center w-auto">
                  <img src="assets/img/logo.png" alt="">
                  <span class="d-none d-lg-block">JadeCare - Login Doctor</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your email & password to login</p>
                  </div>

                  <form method='POST' class="row g-3 needs-validation" novalidate>{% csrf_token %}

                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Email</label>
                      <div class="input-group has-validation">
                        <input type="text" name="email" class="form-control" id="yourUsername" required>
                        <div class="invalid-feedback">Please enter your email.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">Remember me</label>
                      </div>
                    </div>
                    <div>
                       {% for field in form %}
                        <p>
                        {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                      </p>
                    {% endfor %}
                  {% if form.non_field_errors %}
                  <div style="color: red">
                  <p>{{form.non_field_errors}}</p>
                      </div>

                      {% endif %}

                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a href='{% url "accounts:register_doctor" %}'>Create an account</a></p>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0"> <a href='{% url "accounts:login_patient" %}'>Log in as Patient</a></p>
                    </div>
                  </form>

                </div>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

 {% include "base/js2.html" %}

</body>

</html>

accounts/templates/accounts/login_patient.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>JadeCare - Login Patient</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    {% include "base/css2.html" %}

  <style>
    #top-message {
  z-index: 10;
    position: fixed;
    width: 100%;
  height:50px;
  left:50%;
  transform:translateX(-50%);
  top:10px;
}

  </style>
</head>

<body>

<div class="container" id="top-message">
   {% if messages %}
      <div class="alert alert-success messages alert-dismissible fade show" role="alert">
          {% for message in messages %}
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}<br/>
          </span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          {% endfor %}
      </div>
      {% endif %}
</div>


  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href='{% url "welcome_page" %}' class="logo d-flex align-items-center w-auto">
                  <img src="assets/img/logo.png" alt="">
                  <span class="d-none d-lg-block">JadeCare - Login Patient</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your email & password to login</p>
                  </div>

                  <form method='POST' class="row g-3 needs-validation" novalidate>{% csrf_token %}

                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Email</label>
                      <div class="input-group has-validation">
                        <input type="text" name="email" class="form-control" id="yourUsername" required>
                        <div class="invalid-feedback">Please enter your email.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">Remember me</label>
                      </div>
                    </div>
                    <div>
                       {% for field in form %}
                        <p>
                        {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                      </p>
                    {% endfor %}
                  {% if form.non_field_errors %}
                  <div style="color: red">
                  <p>{{form.non_field_errors}}</p>
                      </div>

                      {% endif %}

                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a href='{% url "accounts:register_patient" %}'>Create an account</a></p>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0"> <a href='{% url "accounts:login_doctor" %}'>Log in as Doctor</a></p>
                    </div>
                  </form>



                </div>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

 {% include "base/js2.html" %}

</body>

</html>