appointments/urls.py
from django.urls import path, include

from appointments.views import make_appointment_page, make_appointment_ajax, \
    appointment_detail_page_doc, appointment_detail_page_pat, contact_patient_page, all_appointments_page, \
    appointment_successful_page, make_appointment_post, withdraw_appointment_pat, appointment_medium_page_admin, \
    add_appointment_medium_page_admin, appointment_video_call_page, appointment_text_message_page, \
    appointment_text_message_page_doc, approve_appointment_doc, all_appointments_admin_page, \
    appointment_detail_page_admin

app_name = "appointments"

urlpatterns = [
    path("all_appointments/", all_appointments_page, name="all_appointments"),
    path("all_appointments_admin/", all_appointments_admin_page, name="all_appointments_admin"),
    path("make_appointment/", make_appointment_page, name="make_appointment"),
    path("make_appointment_post/", make_appointment_post, name="make_appointment_post"),
    path("appointment_successful/", appointment_successful_page, name="appointment_successful"),
    path("appointment_detail_doc/<id>/", appointment_detail_page_doc, name="appointment_detail_doc"),
    path("appointment_detail_admin/<id>/", appointment_detail_page_admin, name="appointment_detail_admin"),

    path("appointment_detail_pat/<id>/", appointment_detail_page_pat, name="appointment_detail_pat"),
    path("withdraw_appointment_pat/<id>/", withdraw_appointment_pat, name="withdraw_appointment_pat"),
    path("contact_patient/", contact_patient_page, name="contact_patient"),

    path("make_appointment/", make_appointment_ajax, name="make_appointment_ajax"),

    path("appointment_medium_page_admin/", appointment_medium_page_admin, name="appointment_medium_page_admin"),
    path("add_appointment_medium_page_admin/", add_appointment_medium_page_admin, name="add_appointment_medium_page_admin"),

    path("appointment_video_call_page/", appointment_video_call_page,
         name="appointment_video_call_page"),
    path("appointment_text_message_page/<id>", appointment_text_message_page,
         name="appointment_text_message_page"),
    path("appointment_text_message_page_doc/<id>", appointment_text_message_page_doc,
         name="appointment_text_message_page_doc"),

    path("approve_appointment_doc/<id>/", approve_appointment_doc, name="approve_appointment_doc"),

]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from mysite.views import welcome_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", welcome_page, name="welcome_page"),

    path("home/",  include('home_page.urls', 'home_page')),
    path("accounts/",  include('accounts.urls', 'accounts')),
    path("user_profile/", include('user_profile.urls', 'user_profile')),
    path("posts/", include('posts.urls', 'posts')),
    path("search/", include('search.urls', 'search')),
    path("appointments/", include('appointments.urls', 'appointments')),
    path("general_checkup/", include('general_checkup.urls', 'general_checkup')),
    path("prescriptions/", include('prescriptions.urls', 'prescriptions')),
    path("medical_centers/", include('medical_centers.urls', 'medical_centers')),
    path("communications/", include('communications.urls', 'communications')),
    path("financials/", include('financials.urls', 'financials')),

    # REST-framework
    path('api/accounts/', include('accounts.api.urls', 'accounts_api')),




]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include

from home_page.views import home_page
from posts.views import articles_page_pat, article_detail_page_pat, articles_page_doc, article_detail_page_doc, \
    add_article_page_doc, article_detail_page_admin, articles_page_admin, add_article_page_admin, add_article_post

app_name = "posts"

urlpatterns = [
    path("all_articles_pat/", articles_page_pat, name="all_articles_pat"),
    path("article_detail_pat/<article_id>/", article_detail_page_pat, name="article_detail_pat"),

    path("all_articles_doc/", articles_page_doc, name="all_articles_doc"),
    path("all_articles_admin/", articles_page_admin, name="all_articles_admin"),
    path("article_detail_doc/<article_id>/", article_detail_page_doc, name="article_detail_doc"),
    path("article_detail_admin/<article_id>/", article_detail_page_admin, name="article_detail_admin"),

    path("add_article_doc/", add_article_page_doc, name="add_article_doc"),

    path("add_article_post/", add_article_post, name="add_article_post"),
    path("add_article_admin/", add_article_page_admin, name="add_article_admin"),

]

user_profile/urls.py
from django.urls import path, include

from user_profile.views import patient_profile_page, list_all_doctors_ajax, doctor_profile_page, add_timeslot_doc, \
    view_timeslot_doc, admin_profile_page, list_all_doctors_admin, doctor_detail_admin, \
    list_all_patients_admin, patient_detail_admin, list_all_doctors_schedule_admin

app_name = "user_profile"

urlpatterns = [
    path("patient_profile/", patient_profile_page, name="patient_profile"),
    # path('patient_profile/<user_id>/edit/cropImage/', crop_image, name="crop_image"),
    path("doctor_profile/", doctor_profile_page, name="doctor_profile"),
    path("admin_profile/", admin_profile_page, name="admin_profile"),
    #path("doctor_profile/", DoctorProfileView.as_view(), name="doctor_profile"),
    path("list_all_doctors_ajax/", list_all_doctors_ajax, name="list_all_doctors_ajax"),

    path("add_timeslot_doc/", add_timeslot_doc, name="add_timeslot_doc"),
    path("view_timeslot_doc/", view_timeslot_doc, name="view_timeslot_doc"),


    path("list_all_doctors_admin/", list_all_doctors_admin, name="list_all_doctors_admin"),
    path("doctor_detail_admin/<id>/", doctor_detail_admin, name="doctor_detail_admin"),

    path("list_all_patients_admin/", list_all_patients_admin, name="list_all_patients_admin"),
    path("patient_detail_admin/<id>/", patient_detail_admin, name="patient_detail_admin"),

    path("list_all_doctors_schedule_admin/", list_all_doctors_schedule_admin, name="list_all_doctors_schedule_admin"),

]

templates/base/admin/all_appointment_snippet.html
{% load static %}

<div class="col-12">
                        <div class="card recent-sales top-selling">


                            <div class="card-body">
                                <h5 class="card-title">Recent Appointments <span>| <a href="{% url 'appointments:all_appointments_admin' %}">See all</a></span></h5>

                                <div class="dataTable-wrapper dataTable-loading no-footer sortable searchable fixed-columns">

                                    <div class="dataTable-container">
                                        <table class="table table-borderless datatable dataTable-table">
                                            <thead>
                                            <tr>
                                                <th scope="col" data-sortable="" style="width: 13.5556%;"><a href="#"
                                                                                                             class="dataTable-sorter">Patient</a>
                                                </th>
                                                  <th scope="col" data-sortable="" style="width: 30.1111%;"><a href="#"
                                                                                                             class="dataTable-sorter">Patient Name</a>
                                                </th>
                                                 <th scope="col" data-sortable="" style="width: 13.5556%;"><a href="#"
                                                                                                             class="dataTable-sorter">Doctor</a>
                                                </th>


                                                 <th scope="col" data-sortable="" style="width: 30.1111%;"><a href="#"
                                                                                                             class="dataTable-sorter">Doctor Name</a>
                                                </th>
                                                <th scope="col" data-sortable="" style="width: 25.4444%;"><a href="#"
                                                                                                             class="dataTable-sorter">Problem</a>
                                                </th>
                                                <th scope="col" data-sortable="" style="width: 12.2222%;"><a href="#"
                                                                                                             class="dataTable-sorter">Medium</a>
                                                </th>
                                                <th scope="col" data-sortable="" style="width: 18.6667%;"><a href="#"
                                                                                                             class="dataTable-sorter">Status</a>
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for appointment in appointments_data%}
                                                <tr>
                                            <td scope="row"><a href="{% url 'appointments:appointment_detail_admin' appointment.id %}"><img src="{{appointment.patient.personal_info.photo.url}}" alt=""></a></td>
                                                    <td>{{appointment.patient.last_name}} {{appointment.patient.first_name}}</td>
                                                    <td scope="row"><a href="#"><img src="{{appointment.doctor.user.personal_info.photo.url}}" alt=""></a></td>
                                                    <td>{{appointment.doctor.user.last_name}} {{appointment.doctor.user.first_name}}</td>
                                                <td><a href="#" class="text-primary">{{appointment.appointment_type}}</a></td>
                                                <td>{{appointment.appointment_medium}}</td>
                                                    {% if appointment.status == "Pending" %}
                                                        <td><span class="badge bg-warning">{{appointment.status}}</span></td>
                                                    {% elif appointment.status == "Approved" %}
                                                        <td><span class="badge bg-success">{{appointment.status}}</span></td>
                                                    {% else %}
                                                        <td><span class="badge bg-secondary">{{appointment.status}}</span></td>
                                                    {% endif %}

                                            </tr>
                                            {% endfor %}

                                            </tbody>
                                        </table>
                                    </div>

                                </div>

                            </div>

                        </div>
                    </div>

templates/base/admin/all_patients_snippet.html
{% load static %}

<div class="col-12">
                        <div class="card recent-sales top-selling">


                            <div class="card-body">
                                <h5 class="card-title">New Patients <span>| <a href="{% url 'user_profile:list_all_patients_admin' %}">See all</a></span></h5>

                                <div class="dataTable-wrapper dataTable-loading no-footer sortable searchable fixed-columns">

                                    <div class="dataTable-container">
                                        <table class="table table-borderless datatable dataTable-table">
                                            <thead>
                                            <tr>
                                                <th scope="col" data-sortable="" style="width: 13.5556%;"><a href="#"
                                                                                                             class="dataTable-sorter">Patient</a>
                                                </th>
                                                <th scope="col" data-sortable="" style="width: 32.1111%;"><a href="#"
                                                                                                             class="dataTable-sorter">Full Name</a>
                                                </th>
                                                <th scope="col" data-sortable="" style="width: 12.4444%;"><a href="#"
                                                                                                             class="dataTable-sorter">Gender</a>
                                                </th>
                                                <th scope="col" data-sortable="" style="width: 23.2222%;"><a href="#"
                                                                                                             class="dataTable-sorter">Phone</a>
                                                </th>

                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for patient in all_patient_data %}
                                                <tr>
                                            <td scope="row"><a href="{% url 'user_profile:patient_detail_admin' patient.id %}"><img src="{{patient.user.personal_info.photo.url}}" alt=""></a></td>
                                                <td>{{patient.user.last_name}} {{patient.user.first_name}}</td>
                                                <td>{{patient.user.personal_info.gender}}</td>
                                                <td>{{patient.user.personal_info.phone}}</td>
                                            </tr>
                                            {% endfor %}

                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>

templates/base/admin/recent_news_snippet.html
{% load static %}

<div class="card">
                    <div class="filter">
                        <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                            <li class="dropdown-header text-start">
                                <h6>Filter</h6>
                            </li>

                            <li><a class="dropdown-item" href="#">Today</a></li>
                            <li><a class="dropdown-item" href="#">This Month</a></li>
                            <li><a class="dropdown-item" href="#">This Year</a></li>
                        </ul>
                    </div>

                    <div class="card-body pb-0">
                        <h5 class="card-title">News &amp; Updates <span>| See all</span></h5>

                        {% for post in all_posts_data %}
                            <div class="news">
                            <div class="post-item clearfix">
                                <img src="{{post.post_files.all.0.file.url}}" alt="">
                                <h4><a href="{% url 'posts:article_detail_admin' post.id  %}">{{post.name}}</a></h4>
                                <p>{{post.body|truncatechars:150}}</p>
                                <p>{{post.created_at|timesince}}</p>
                            </div>


                        </div><!-- End sidebar recent posts-->
                        {% endfor %}

                    </div>
                </div>